Incluido testes unitarios e sonarqube

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -6,8 +6,52 @@ on:
       - master
 
 jobs:
+  run-tests:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout do repositório
+      uses: actions/checkout@v2
+
+    - name: Efetua instalação de dependências
+      run: |
+        npm install
+
+    - name: Executa teste da aplicação
+      run: |
+        npm run test
+
+  run-sonarqube:
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/master'
+    needs:
+      - run-tests
+
+    steps:
+    - name: Checkout do repositório
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+
+    - name: SonarQube Scan
+      uses: sonarsource/sonarqube-scan-action@master
+      continue-on-error: false
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+    - name: Valida Quality Gate status do SonarQube
+      run: |
+        if [ "$(curl -s -u ${{ secrets.SONAR_TOKEN }}: ${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=pixel-pizza3-lambdas | jq -r '.projectStatus.status')" != "OK" ]; then
+          echo "Quality Gate failed. Exiting with non-zero status."
+          exit 1
+        fi
+
   build:
     runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/master'
+    needs:
+      - run-tests
+      - run-sonarqube
 
     steps:
       - name: Checkout do repositório
